/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Money {
    private  int amount;
    private  String currency;

    public Money(int amount, String currency){
      if (amount < 0){
        throw new IllegalArgumentException();
      }

      if (currency == null || currency.isEmpty()){
        throw new IllegalArgumentException();
      }
      this.amount = amount;
      this.currency = currency;
    }

    public int getAmount(){
      return amount;
    }

    public String getCurrency(){
      return currency;
    }

    public void addAmount(int newAmount){
      this.amount += newAmount;
    }

    public boolean equals(Object anObject){
      if (anObject instanceof Money){
        Money money = (Money) anObject;
        return money.getCurrency().equals(getCurrency())
        && getAmount() == money.getAmount();
      }
      return false;
    }
}
